### ISSUE TITLE
invalid checksum

### ISSUE THREAD

**Issue by Thesane** [ros-drivers/microstrain_3dmgx2_imu#4]
I am trying to connect to microstrain 3dm-gx3-45 device but I am getting always invalid checksum. However, the example from microstrain website can connect to the device without any problems and with no errors.
I am using Serial-to-USB converter with device as we have the serial version.
I'm not sure what is the problem?
please help
here is the link for the examples from microstrain
http://files.microstrain.com/MIP%20C%20Code%20Sample%20Windows%20and%20Linux.zip

**Comment by chadrockey** [comment]
Hi Tesane,

I unfortunately don't have one of those IMUs so I'm not sure how to help you.  If you manage to figure it out, please submit a pull request and I'll do my best to merge it into the main driver.

Thank you.

**Comment by ZdenekM** [comment]
Thesane,

I've implemented simple driver for this device: https://github.com/ZdenekM/microstrain_3dm_gx3_45. It's not well tested but it works somehow.

**Comment by Thesane** [comment]
Chadrockey, thanks but I thought this driver with for this model as well. 
I'm using it on corobot with groovy.
I tried to track it in the source code and I think it fails in the checksum comparison in the end of receive function. Any hints will be really appreciated.

**Comment by Thesane** [comment]
ZdenekM, I already tried this one but I think it has some compatibility issues with groovy. I'm getting an error that imu_driver not found when I use roslaunch and missing geoinfo msgs in python if I used rosrun. I installed geodesy and uuid_msgs packages but still getting the same error

**Comment by Thesane** [comment]
ZdenekM, I already tried this one but I think it has some compatibility issues with groovy. I'm getting an error that imu_driver not found when I use roslaunch and missing geoinfo msgs in python if I used rosrun. I installed geodesy and uuid_msgs packages but still getting the same error
